name: Testes Cypress

on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    branches-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependências
        run: npm install

      - name: Executar testes com o Cypress
        run: npm run cypress:run
